/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
  * @author Liborio Castañeda - Javier Cervantes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnNuevoProducto = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnVenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnMercancia = new javax.swing.JMenuItem();
        MnClientes = new javax.swing.JMenuItem();
        mnFacturas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centro Comercial - Bienvenidos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 0, 0));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jMenu1.setText("Sistema");
        jMenu1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        mnNuevoProducto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        mnNuevoProducto.setText("Registrar Producto");
        mnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNuevoProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnNuevoProducto);

        jMenuItem6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItem6.setText("Registrar Cliente");
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator1);

        mnSalir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Pedidos");
        jMenu3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        mnVenta.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        mnVenta.setText("Agregar Venta");
        jMenu3.add(mnVenta);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Reportes");
        jMenu2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        mnMercancia.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        mnMercancia.setText("Mercancia");
        jMenu2.add(mnMercancia);

        MnClientes.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        MnClientes.setText("Clientes");
        jMenu2.add(MnClientes);

        mnFacturas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        mnFacturas.setText("Facturas");
        jMenu2.add(mnFacturas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(476, 318));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNuevoProductoActionPerformed
        Nuevo n = new Nuevo(this,true);
            n.setVisible(true);
    }//GEN-LAST:event_mnNuevoProductoActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnFacturas;
    private javax.swing.JMenuItem mnMercancia;
    private javax.swing.JMenuItem mnNuevoProducto;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnVenta;
    // End of variables declaration//GEN-END:variables
}
