/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class RegistrarClientes extends javax.swing.JDialog {

    String ruta;
    ObjectOutputStream salida;
    ArrayList<Persona> personas;
    Persona c;
    int botones = 0;

    /**
     * Creates new form RegistroCliente
     */
    public RegistrarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            initComponents();
            ruta = "src/datos/personas.txt";
            personas = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
            Helper.volcadoClientes(salida, personas);
            Helper.limpiarTabla(tblPersonas);
            Helper.llenadoTablaClientes(tblPersonas, ruta);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        JButton botonesH[] = {cmdGuardar, cmdSalir};
        JButton botonesD[] = {cmdCancelar, cmdModificar, cmdEliminar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Clientes");

        jPanel1.setToolTipText("Registro De Clientes");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sexo");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 40));

        jLabel2.setText("Nombre");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 30));

        jLabel3.setText("Apellido");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 30));

        jLabel4.setText("Cédula");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 170, -1));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, -1));

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel3.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 170, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Sin definir" }));
        jPanel3.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 200));

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Cédula", "Nombre", "Apellido", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 590, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 30));

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 30));

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));

        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 180, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(629, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtCedula.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por Favor Digite La Cedula Del Cliente", "Error", 2);
            txtCedula.requestFocusInWindow();
            botones = 1;
        } else if (txtNombre.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por Favor Digite El Nombre Del Cliente", "Error", 2);
            txtNombre.requestFocusInWindow();
            botones = 1;
        } else if (txtApellido.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por Favor Digite El Apellido Del Cliente", "Error", 2);
            txtApellido.requestFocusInWindow();
            botones = 1;
        } else if (Helper.buscarPorCedula(txtCedula.getText(), ruta)) {
            Helper.mensaje(this, "Este Cliente Ya Existe, Por Favor Modifique sus datos", "Error", 2);
            txtNombre.requestFocusInWindow();
            txtCedula.setEnabled(false);
            JButton botonesH[] = {cmdModificar, cmdSalir, cmdCancelar};
            JButton botonesD[] = {cmdGuardar, cmdEliminar};
            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
            botones = 0;
        } else {
            try {
                String Cedula, Nombre, Apellido, Sexo;

                Cedula = txtCedula.getText();
                Nombre = txtNombre.getText();
                Apellido = txtApellido.getText();
                Sexo = (String) cmbSexo.getSelectedItem();

                Persona c = new Persona(Cedula, Nombre, Apellido, Sexo);

                c.guardar(salida);
                Helper.llenadoTablaClientes(tblPersonas, ruta);
            } catch (IOException ex) {
                Logger.getLogger(ex.getMessage());
            }
        }
        if (botones == 1) {
            JButton botonesH[] = {cmdGuardar, cmdSalir, cmdCancelar};
            JButton botonesD[] = {cmdModificar, cmdEliminar};
            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void tblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonasMouseClicked
        int i;

        personas = Helper.traerDatos(ruta);
        i = tblPersonas.getSelectedRow();
        c = personas.get(i);

        txtCedula.setText(String.valueOf(c.getCedula()));
        txtNombre.setText(c.getNombre());
        txtApellido.setText(c.getApellido());
        cmbSexo.setSelectedItem(c.getSexo());

        JButton botonesH[] = {cmdGuardar, cmdSalir, cmdEliminar, cmdCancelar, cmdModificar};
        JButton botonesD[] = {};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

    }//GEN-LAST:event_tblPersonasMouseClicked

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;

        op = JOptionPane.showConfirmDialog(this, "¿Seguro Que Desea Eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {

            try {
                i = tblPersonas.getSelectedRow();
                personas.remove(i);
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
                Helper.volcadoClientes(salida, personas);
                Helper.llenadoTablaClientes(tblPersonas, ruta);
                txtNombre.setText("");
                txtCedula.setText("");
                txtApellido.setText("");
                txtCedula.requestFocusInWindow();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ListadoClientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ListadoClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed
    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        txtCedula.setText("");
        txtCedula.setEnabled(true);
        txtNombre.setText("");
        txtApellido.setText("");
        cmbSexo.setSelectedIndex(0);
        JButton botonesH[] = {cmdGuardar, cmdSalir, cmdCancelar};
        JButton botonesD[] = {cmdModificar, cmdEliminar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isAlphabetic(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isAlphabetic(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        if (txtCedula.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por Favor Digite La Cedula Del Cliente", "Error", 1);
            txtCedula.requestFocusInWindow();
        } else if (txtNombre.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por Favor Digite El Nombre Del Cliente", "Error", 1);
            txtNombre.requestFocusInWindow();
        } else if (txtApellido.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por Favor Digite El Apellido Del Cliente", "Error", 1);
            txtApellido.requestFocusInWindow();
        } else {
            try {
                String cedula, nombre, apellido, sexo;
                ArrayList<Persona> personasActualizado;

                cedula = txtCedula.getText();
                nombre = txtNombre.getText();
                apellido = txtApellido.getText();
                sexo = (String) cmbSexo.getSelectedItem();

                personasActualizado = Helper.actualizarPersona(ruta, cedula, nombre, apellido, sexo);
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
                Helper.volcado(salida, personasActualizado);
                Helper.llenadoTablaClientes(tblPersonas, ruta);
                Helper.mensaje(this, "Datos modificados exitosamente", "Información", 1);

            } catch (IOException ex) {
                Logger.getLogger(RegistrarClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarClientes dialog = new RegistrarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
